### ISSUE TITLE
ngrok我终于懂了 - Onns Blog

### ISSUE THREAD

**Issue by onns** [onns/onns.xyz#173]
https://onns.xyz/blog/2020/12/09/ngrok-doc/ 

 ngrok我终于懂了

**Comment by onns** [comment]
20210107更新：

与`TCP`协议不同的是，ngrok的HTTP/HTTPS协议的端口无法通过`remote_port`参数在客户端指定，而是在服务端预先已经指定好的：`-httpAddr=":82" -httpsAddr=":83"`。

ngrok的http协议通过不同的子域名来区别服务类型，所以配置方法是：

```yaml
  nginx:
    subdomain: "io"
    proto:
      http: "192.168.1.119:80"
```
